### ISSUE TITLE
Checkout Failed

### ISSUE THREAD

**Issue by cvanem** [1fge/open-supreme#12]
I recently tested this and can get to the final stage of sending the checkout data, but every time the checkout fails and no errors or information is provided other than a "failed" status. I have tried:

- Added a valid token to the g-recaptcha-response field when submitting.
- I double checked all of the headers and form values against a known working HTTP post and everything looks good.
- I ported the code to node.js and have the same problem.

@1fge @NicPav1 Any hints as to what may be wrong or what needs to be fixed?  I wouldn't mind doing a PR, but I am unsure how to fix the problem at this point?  The only thing I can think of is something with the ticket system and/or cookies may be blocking it?

**Comment by 6missedcalls** [comment]
Do you have a discord by any chance?

**Comment by NicPav1** [comment]
Pretty sure it’s because of the ticket system Supreme uses

**Comment by cvanem** [comment]
Ok thanks.  I see ticket.js is live on their site, so that must be what is causing the failure.

**Comment by 1fge** [comment]
@cvanem Yep, that's most likely being caused by ticket. I'd also make sure that you solve the captcha **After** adding to cart.

**Comment by cvanem** [comment]
@1fge Thanks for the info.  I pretty much gave up on a request based python solution and have migrated to a hybrid nodejs puppeteer + request + local harvester solution.  I have had some success with ~4-6s checkout times while ticketing is active.  Although something broke with the last restock push that I am still trying to figure out.

I have been solving captcha's before adding to cart and have had success, but I will try doing a few after adding to cart.  Are the token's timestamped, I wasn't aware that they could be validated in that way?

**Update:** The captcha timing does seem to be important as I just had a success with solving after adding to cart.

Also, do you know if 4-6s checkout times even feasible for success during a main drop, or does it need to be faster?

**Comment by 1fge** [comment]
Glad to hear you are having success after switching around the captcha 😄 And if you are able to consistently checkout each week with 4-6 second speeds, that’s pretty good in my opinion.
