### ISSUE TITLE
Can't find 'chk'

### ISSUE THREAD

**Issue by elmuchu** [1fge/open-supreme#15]
Hello, I tried using your program, but I get a KeyError in the 'parse_for_styles' function, as it does not seem to find the 'chk' key in the 'stylename' dictionnary.
I listed every key and values associated for each 'stylename' dictionnary that is retrieved, but I don't see a 'chk' key anywhere.
Could you tell me what this key is supposed to represent ?

**Comment by 1fge** [comment]
As mentioned in the README, the bot only works for Supreme US. As far as I know, the chk attribute isn't required for other regions like Supreme EU, so that's most likely why you're getting the error.

**Comment by elmuchu** [comment]
Ok, thank you, I'll try to find the equivalent for Supreme EU.
Thank you again for all your amazing work !

**Comment by 1fge** [comment]
Sure thing!

**Comment by koekiedealer** [comment]
> Ok, thank you, I'll try to find the equivalent for Supreme EU.
> Thank you again for all your amazing work !

I'm trying to do the same, don't really know what I'm searching for though. Did you manage to rebuild the bot so that it works in the EU?

**Comment by elmuchu** [comment]
No, I tried to retrieve the infos from the US shop, but I couldn't even manage to reach it (black screen, no items showing). This might come from my badly configured VPN... I may try again this weekend

**Comment by koekiedealer** [comment]
Got exactly the same problem, can't manage to get on the working US Supreme site...

**Comment by koekiedealer** [comment]
tried again this weekend. Removed all the chk attributes and tried running it. The bot gets stuck on a loop of looking for the product and searching for "____" and repeats... Can't manage to get any further
