### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by makovez** [1fge/open-supreme#19]

**Comment by 1fge** [comment]
Whenever I stop maintaining the bot, I will update the README to include that it no longer works. Up until that point, you can trust that the README provides a fairly accurate description of its capabilities. With that being said, the program is still working as long as Supreme's bot protection is disabled.

**Comment by makovez** [comment]
that's good.

**Comment by makovez** [comment]
i'm working with some guys in akamai for nike api, if you wanna join us text me on telegram [@soermejo](https://t.me/soermejo)
