### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by mlafortune1223** [1fge/open-supreme#22]
Michaels-MacBook-Pro:open-supreme michaellafortune$ pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Defaulting to user installation because normal site-packages is not writeable
Collecting beautifulsoup4==4.7.1
  Using cached beautifulsoup4-4.7.1-py2-none-any.whl (94 kB)
Collecting captcha-harvester==2.1.1
  Using cached captcha-harvester-2.1.1.tar.gz (35 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rv/qb9xhw_j5cz1vh7wy75tmpsw0000gn/T/pip-install-MGQuF_/captcha-harvester/setup.py'"'"'; __file__='"'"'/private/var/folders/rv/qb9xhw_j5cz1vh7wy75tmpsw0000gn/T/pip-install-MGQuF_/captcha-harvester/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rv/qb9xhw_j5cz1vh7wy75tmpsw0000gn/T/pip-pip-egg-info-16pGI3
         cwd: /private/var/folders/rv/qb9xhw_j5cz1vh7wy75tmpsw0000gn/T/pip-install-MGQuF_/captcha-harvester/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rv/qb9xhw_j5cz1vh7wy75tmpsw0000gn/T/pip-install-MGQuF_/captcha-harvester/setup.py", line 3, in <module>
        import harvester
      File "harvester/__init__.py", line 1, in <module>
        from harvester import browser, fetch, server
      File "harvester/browser.py", line 31
        def read_osx_defults(plist: str, binary: str) -> str:
                                  ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by LicketySpliket** [comment]
Hey @mlafortune1223, I'm not sure why you are trying to use Python 2.7 for this project (aside from the fact that it's the default MacOS Python installation). Make sure you are running `python3` in your terminal. Moreover, make sure you have Python 3.x installed.
