### ISSUE TITLE
Discord Invite Invalid

### ISSUE THREAD

**Issue by joemo58** [1fge/open-supreme#6]
![image](https://user-images.githubusercontent.com/18613317/81937050-fa278000-95ea-11ea-9f3e-beaa4bff9d0e.png)

Can I get another invite link to the discord?

**Comment by tomboylover** [comment]
I think the og dev is now working on a payed service so his invite might of got shut down

**Comment by 1fge** [comment]
Unfortunately the discord server for Open-Supreme is no longer active.
